service: transit 
runtime: python37

basic_scaling:
    max_instances: 2
    idle_timeout: 20m

resources:
    cpu: 2
    memory_gb: 2
    disk_size_gb: 10

entrypoint: gunicorn -b 0.0.0.0:8080 app:server




