= This is chattanooga data prep

This folder contains a Jupyter Notebook that explains how the Chattanooga dataset used in the dashboard was created. The dataset comes from a join of CARTA RideCheck (automatic passenger counter) data and static GTFS feeds.


*Field Definitions For Dashboard Data* (actual data is located under data/chattanooga in a .pbz2 file):

- *trip_id:* same as GTFS
- *arrival_time:* same as GTFS
- *stop_id:* same as GTFS
- *stop_sequence:* same as GTFS
- *stop_name:* same as GTFS
- *stop_lat:* same as GTFS
- *stop_lon:* same as GTFS
- *route_id::* same as GTFS
- *direction_id:* same as GTFS
- *board_count:* number of people getting ON the bus at the stop (PASSENGERS_ON in RideCheck data)
- *alight_count:* number of people getting OFF the bus at the stop (PASSENGERS_OFF in RideCheck data)
- *direction_desc:* the direction of the bus, either INBOUND or OUTBOUND (DIRECTION_NAME in RideCheck data)
--- *TO FIX: see issue tracker*
- *service_period:* one of the following: Weekday, Saturday, or Sunday
- *date:* the date of the data in YYYY-MM-DD format
- *date_time:* date + " " + arrival_time
- *trip_start_time:* the earliest known stop time on the trip
--- *TO FIX: see issue tracker*
- *trip_name:* trip_start_time + " (TRIP ID: " + trip_id + ")"
- *day_of_week:* a value from 0 - 6, where Monday = 0, Tuesday = 1, ... Sunday = 6
